### ISSUE TITLE
No such file or directory : default.yml

### ISSUE THREAD

**Issue by willhunger** [acyortjs/acyort#34]
When I trigger travis-ci build, I find these logs for error.
```
{ Error: ENOENT: no such file or directory, open '/home/travis/build/willhunger/Blog/themes/donob/i18n/default.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Helper.resetLocales (/home/travis/.nvm/versions/node/v6.0.0/lib/node_modules/acyort/lib/generator/helper/index.js:36:41)
    at Generator.genHtmls (/home/travis/.nvm/versions/node/v6.0.0/lib/node_modules/acyort/lib/generator/index.js:47:18)
    at Generator.generate (/home/travis/.nvm/versions/node/v6.0.0/lib/node_modules/acyort/lib/generator/index.js:107:19)
    at _fetcher.fetch.then.then.data (/home/travis/.nvm/versions/node/v6.0.0/lib/node_modules/acyort/lib/acyort.js:17:35)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/travis/build/willhunger/Blog/themes/donob/i18n/default.yml' }
```
But build exited with 0. 
How to deal with it?

**Comment by LoeiFy** [comment]
@willhunger now fixed, you can trigger travis ci rebuild

**Comment by willhunger** [comment]
Now it worked well.Thanks.
